# Generated by Django 5.0.3 on 2024-04-27 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bugreport",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="featurerequest",
            name="priority",
        ),
        migrations.AddField(
            model_name="bugreport",
            name="proirity",
            field=models.PositiveIntegerField(
                default=5, validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
        migrations.AddField(
            model_name="featurerequest",
            name="proirity",
            field=models.PositiveIntegerField(
                default=5, validators=[django.core.validators.MaxValueValidator(5)]
            ),
        ),
    ]
