# Generated by Django 5.0.3 on 2024-04-27 20:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quality_control", "0003_rename_proirity_bugreport_priority_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="featurerequest",
            old_name="escription",
            new_name="description",
        ),
    ]
